#!/bin/sh
myip=`wget http://ipecho.net/plain -O - -q ; echo`
echo 'net.ipv4.ip_forward=1' >/etc/sysctl.conf
sysctl -p
iptables -t nat -A POSTROUTING -s 192.0.0.0/8 -o eth0 -j MASQUERADE
iptables -t nat -A POSTROUTING -s 192.0.0.0/8 -j SNAT --to-source $myip
iptables -t nat -A POSTROUTING -j MASQUERADE
iptables -A INPUT -p TCP --dport 440 -j ACCEPT
iptables -A INPUT -p TCP --dport 22 -j ACCEPT
iptables -A INPUT -p TCP --dport 137 -j ACCEPT
iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-port 137
iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
service iptables save
service iptables restart
chkconfig iptables on
setenforce 0

